### ISSUE TITLE
4.4.0-RC0 Release Checklist

### ISSUE THREAD

**Issue by jwiley84** [Microsoft/BotBuilder#5375]
## Package Location
https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily
https://botbuilder.myget.org/gallery/botbuilder-v4-js-daily

## Change Notes
In this release, the team focused on improving and simplifying message and activities handling. The [Bot Framework Activity Schema](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-activity.md#conversation-update-activity) is the underlying schema used to define the interaction model for bots. 

Review all changes that went into 4.4 in the detailed change logs:
[[Change Log for .NET](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.4+)]   [[Change Log for Node.js](https://github.com/Microsoft/botbuilder-js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A4.4+)] 

## GitHub Updates
**Create New Branch** @cleemullins
- [X] C#   [4.4](https://github.com/Microsoft/botbuilder-dotnet/tree/4.4)
- [x] JS [4.4](https://github.com/Microsoft/botbuilder-js/tree/4.4)

**Setup Branch Protection on New Branch** @cleemullins
- [X] C#
- [x] JS

**Bump Version on Master** @cleemullins
- [ ] C#
- [ ] JS

**Update Readme.md in master to reflect new branch** @cleemullins
- [X] C#
- [x] JS

**Create DRAFT Release** @cleemullins
- [X] C# [4.4](https://github.com/Microsoft/botbuilder-dotnet/releases/tag/untagged-f1f2d9e1924fc4e02d01)
- [x] JS [4.4](https://github.com/Microsoft/botbuilder-js/releases/edit/untagged-ef83f22873d4bb85ab38)

**Write release notes and change log** @CoHealer 
- [x] C#
- [x] JS

**Update road-map** @yochay 
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Apply Release Notes to DRAFT Release** @CoHealer 
- [x] C#
- [x] JS

**Publish GitHub Release** @cleemullins 
- [ ] C#
- [ ] JS

## Required Signoff

**Teams**  @CoHealer, Sid Uppal
- [ ] C#
- [ ] JS

**Cortana** @CoHealer, bw-kforce-ms
- [ ] C#
- [ ] JS

**Virtual Assistant** @CoHealer, @darrenj 
- [ ] C#
- [ ] JS

## Testing Status @jwiley84 
**Console Adapter**
- [x] C#
- [x] JS

**Simple Dialog Flow**
- [x] C#
- [x] JS

**Simple State Management**
- [x] C#
- [x] JS

**Welcome Messages**
- [x] C#
- [x] JS

**Prompts and Prompt Validations**
- [x] C#
- [x] JS

**Standard Cards**
- [x] C#
- [x] JS

**Adaptive Cards**
- [X] C#
- [x] JS

**Card Actions**
- [X] C#
- [x] JS

**Regex Checking**
- [X] C#
- [x] JS

**QnA Maker**
- [X] C#
- [x] JS

**LUIS**
- [X] C#
- [x] JS

**Dispatch**
- [X] C#
- [x] JS

**Attachments**
- [X] C#
- [x] JS

**Proactive Messages**
- [X] C#
- [x] JS

**Middlware**
- [X] C#
- [x] JS

**Translations**
- [X] C#
- [x] JS

**Authentication**
- [X] C#
- [x] JS

**Waterfalls and Dialog Sets**
- [X] C#
- [x] JS

**State Storage**
- [X] C#

**Transcript Logging**
- [x] JS

**Facebook-specific Events**
- [X] C#
- [x] JS

**Cortana Skills (not tested on Cortana channel)**
- [x] C#
- [x] JS

**Application Insights**
- [X] C#
- [x] JS

**Teams**
- [X] C#
- [x] JS

**Enterprise Bot Template**
- [X] C#

**Comment by yochay** [comment]
@cleemullins

**Comment by CoHealer** [comment]
Closing, new RC checklist being tracked with https://github.com/Microsoft/BotBuilder/issues/5377
